### ISSUE TITLE
Flexible field titles missing after initial save

### ISSUE THREAD

**Issue by schrapel** [reaktivstudios/cmb2-flexible-content#13] opened 2017-07-07 14:10 UTC
When you add a flexible field the title is displayed next to the red `x` but after a save they are not loaded on page load

<img width="867" alt="screenshot 2017-07-07 16 09 04" src="https://user-images.githubusercontent.com/3613405/27961385-bffd9eb0-632e-11e7-8332-3ed18b9dcb36.png">

**Comment by jjeaton** [comment] 2017-07-07 14:25
Can you share the field definition so I can attempt to reproduce? We did 
not see this in our testing, but we do have at least one bugfix already 
committed to master.

**Comment by retober** [comment] 2018-03-19 01:07
In the provided screenshot it seems that it is possible to reorder the created field groups. I am not able to reproduce this behavior, was this removed or am I missing something. Sorry for not contributing to this issue but I didn't want to open a new one.

**Closed** 2018-11-05 21:32 UTC
